name: 'Switch Action'
description: 'GitHub workflow to send message on switch.'
inputs:
  token:
    description: "Switch's bot token"
    required: true
  message:
    description: message to send on switch.
  document:
    description: file path to send
  description:
    description: file's description
  channel_id:
    description: Switch's channel ID.
  group_id:
    description: Switch'S Group ID.
  user_id:
    description: Switch'S User ID.

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: 'message-square'
  color: 'blue'