name: Post on Switch

on:
  workflow_dispatch:

jobs:
  with:
    name: Task   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: ./
      with:
        token: ""
