name: Post on Switch

on:
  workflow_dispatch:

jobs:
  with:
    name: Task   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send message
      uses: "./"
      with:
        token: ${{ secrets.BOT_TOKEN }}
        message: "Hi"
        user_id: 972
    - name: Get cat image
      run: |
        wget -O cat.png https://cataas.com/cat

    - name: send media file
      uses: "./"
      with:
        token: ${{ secrets.BOT_TOKEN }}
        message: "CheckOut this cool cat!"
        thumb: 'cat.png'
        document: 'cat.png'
        user_id: 972
        button_text: "Hello User"
        button_url: "https://github.com/New-dev0"

